### ISSUE TITLE
npm i Doesn't Work

### ISSUE THREAD

**Issue by TomPridham** [zacanger/hey-you#4]
Using `npm i -g hey-you` doesn't work.

Error: ```/usr/local/bin/hey-you-cli -> /usr/local/lib/node_modules/hey-you/cli.js
/usr/local/bin/hey-you -> /usr/local/lib/node_modules/hey-you/index.js
/usr/local/bin/heyyou -> /usr/local/lib/node_modules/hey-you/index.js
/usr/local/bin/heyyou-cli -> /usr/local/lib/node_modules/hey-you/cli.js
/usr/local/bin/hey -> /usr/local/lib/node_modules/hey-you/index.js
/usr/local/bin/hey-cli -> /usr/local/lib/node_modules/hey-you/cli.js

> electron@1.6.11 postinstall /usr/local/lib/node_modules/hey-you/node_modules/electron
> node install.js

/usr/local/lib/node_modules/hey-you/node_modules/electron/install.js:47
  throw err
  ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/hey-you/node_modules/electron/.electron'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.6.11 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.6.11 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```

Log: [2017-06-27T22_57_13_338Z-debug.txt](https://github.com/zacanger/hey-you/files/1107074/2017-06-27T22_57_13_338Z-debug.txt)

**Comment by zautumnz** [comment]
At first glance this looks like an issue with permissions. Do you own `/usr/local/lib`? (Do you normally have to install global modules with `sudo`?) Also, did Electron make a dir at `~/.electron` with the right permissions (should look like `drwxr-xr-x`)? If not, `mkdir ~/.electron && chmod 755 ~/.electron` and let me know if that works. I've seen some possibly related bugs [here](https://github.com/electron/electron/issues/1709), [here](https://github.com/electron-userland/electron-prebuilt/issues/27), and [here](https://github.com/electron-userland/electron-prebuilt/issues/48).

**Comment by TomPridham** [comment]
I do normally have to use `sudo` to install things globally. I did that the first time as well as after I did `mkdir ~/.electron && chmod 755 ~/.electron`
Running `sudo npm install -g electron-prebuilt --unsafe-perm=true --allow-root` from the last issue you linked worked.

**Comment by zautumnz** [comment]
Thanks! I added a note in the README about this.
